# 990万次骑行: 纽约自行车共享系统分析

In [18]:
import numpy as np
import pandas as pd
import time,datetime
import matplotlib.pyplot as plt

In [19]:
%matplotlib inline

In [20]:
%pylab
%matplotlib notebook

Using matplotlib backend: Qt5Agg
Populating the interactive namespace from numpy and matplotlib


In [4]:
cb1 = pd.DataFrame(pd.read_csv('d:/pydata/citibike/201501-citibike-tripdata.csv'))
cb2 = pd.DataFrame(pd.read_csv('d:/pydata/citibike/201502-citibike-tripdata.csv'))
cb3 = pd.DataFrame(pd.read_csv('d:/pydata/citibike/201503-citibike-tripdata.csv'))
cb4 = pd.DataFrame(pd.read_csv('d:/pydata/citibike/201504-citibike-tripdata.csv'))
cb5 = pd.DataFrame(pd.read_csv('d:/pydata/citibike/201505-citibike-tripdata.csv'))
cb6 = pd.DataFrame(pd.read_csv('d:/pydata/citibike/201506-citibike-tripdata.csv'))
cb7 = pd.DataFrame(pd.read_csv('d:/pydata/citibike/201507-citibike-tripdata.csv'))
cb8 = pd.DataFrame(pd.read_csv('d:/pydata/citibike/201508-citibike-tripdata.csv'))
cb9 = pd.DataFrame(pd.read_csv('d:/pydata/citibike/201509-citibike-tripdata.csv'))
cb10 = pd.DataFrame(pd.read_csv('d:/pydata/citibike/201510-citibike-tripdata.csv'))
cb11 = pd.DataFrame(pd.read_csv('d:/pydata/citibike/201511-citibike-tripdata.csv'))
cb12 = pd.DataFrame(pd.read_csv('d:/pydata/citibike/201512-citibike-tripdata.csv'))

In [5]:
cb = pd.concat([cb1,cb2,cb3,cb4,cb5,cb6,cb7,cb8,cb9,cb10,cb11,cb12],ignore_index=False) #ignore_index=False,不忽略索引
cb['tripduration'] = cb['tripduration'].astype('float64')#改变数据类型，因为数据量大，原本的位数不够用

In [6]:
#共有9937969条数据（骑行次数）
cb.shape

(9937969, 15)

In [7]:
#共有497个租赁点
len(cb['start station name'].unique())

497

In [8]:
#共有8477辆自行车
len(cb['bikeid'].unique())

8477

In [9]:
#每辆自行车的被租借频率
len(cb['bikeid'])/len(cb['bikeid'].unique())

1172.3450513153239

In [10]:
#每辆自行车平均每日的租借频率
cb['bikeid'].count()/len(cb['bikeid'].unique())/365

3.2119042501789696

In [11]:
#每次租借平均时长
cb['tripduration'].mean()/60

16.134794237132358

# 2015年Citi Bike每月骑行次数

In [27]:
cb['starttime']=pd.to_datetime(cb['starttime'])

In [28]:
cb = cb.set_index('starttime')

In [245]:
cb_month = cb.resample('M',how=len)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: FutureWarning: how in .resample() is deprecated
the new syntax is .resample(...)..apply(<func>)
  if __name__ == '__main__':


In [246]:
group_cb_month = cb_month['bikeid']

In [247]:
group_cb_month

starttime
2015-01-31     285552
2015-02-28     196930
2015-03-31     341826
2015-04-30     652390
2015-05-31     961986
2015-06-30     941219
2015-07-31    1085676
2015-08-31    1179044
2015-09-30    1289699
2015-10-31    1212277
2015-11-30     987245
2015-12-31     804125
Freq: M, Name: bikeid, dtype: int64

In [248]:
plt.rc('font',family='STXihei',size=15)

In [249]:
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [285]:
#2015年Citi Bike每月骑行次数
plt.plot(group_cb_month,'g8',group_cb_month,'g-',color='#39A2E1',linewidth=3,markeredgewidth=3,markeredgecolor='#39A2E1',alpha = 0.8)
plt.xlabel('月份')
plt.ylabel('租赁骑行次数')
plt.title('2015年Citi Bike每月骑行次数')
plt.grid(color='#95a5a6',linestyle='--',linewidth=1,axis='y',alpha=0.4)

In [251]:
plt.xticks(a,('1月','2月','3月','4月','5月','6月','7月','8月','9月','10月','11月','12月'))

([<matplotlib.axis.XTick at 0x28118c4a860>,
 <a list of 12 Text xticklabel objects>)

# 2015年Citi Bike每季度骑行次数

In [253]:
cb_quarterly = cb.resample('Q',how=len)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: FutureWarning: how in .resample() is deprecated
the new syntax is .resample(...)..apply(<func>)
  if __name__ == '__main__':


In [255]:
group_cb_quarterly = cb_quarterly['bikeid']

In [260]:
group_cb_quarterly

starttime
2015-03-31     824308
2015-06-30    2555595
2015-09-30    3554419
2015-12-31    3003647
Freq: Q-DEC, Name: bikeid, dtype: int64

In [257]:
plt.rc('font', family='STXihei', size=15)

In [258]:
a = np.array([1,2,3,4])

In [305]:
#2015年Citi Bike每季度骑行次数
plt.bar([1,2,3,4],group_cb_quarterly,color='#39A2E1',alpha=0.8,align='center',edgecolor='white')
plt.xlabel('季度')
plt.ylabel('租赁骑行次数')
plt.title('2015年Citi Bike每季度骑行次数')
plt.legend(['次数'],loc='upper right')
plt.grid(color='#95a5a6',linestyle='--',linewidth=1,axis='y',alpha=0.4)
plt.xticks(a,('一季度','二季度','三季度','四季度'))

([<matplotlib.axis.XTick at 0x28119919e80>,
 <a list of 4 Text xticklabel objects>)

# 用户年龄分布图

In [288]:
user_gender = cb.groupby('gender')['bikeid'].agg(len)/cb["bikeid"].count()*100

In [289]:
user_gender

gender
0    13.303302
1    66.501807
2    20.194891
Name: bikeid, dtype: float64

In [293]:
plt.rc('font',family='STXihei',size=15)
colors = ['#052B6C','#39A2E1','#EA1F29']
name = ['未知','男性','女性']

In [295]:
#Citi Bike用户性别占比
plt.pie(user_gender,labels=name,colors=colors,explode=(0,0,0),startangle=60,autopct='%1.1f%%')
plt.title('Citi Bike用户性别占比')
plt.legend(['未知','男性','女性'],loc='upper left')

In [ ]:
#查看所有用户年龄分布
cb['birth year'].min(),cb['birth year'].max()
cb['age']=2015-cb['birth year']
cb['age'].min(),cb['age'].max()

In [303]:
#对年龄进行分组汇总
bins = [0,18,30,50,131]
group_age = ['少年','青年','中年','老年']
cb['group_age']= pd.cut(cb['age'],bins,labels=group_age)
user_age = cb.groupby('group_age')['group_age'].agg(len)

In [304]:
#用户年龄分布图
plt.rc('font',family='STXihei',size=15)
a = np.array([1,2,3,4])
plt.bar([1,2,3,4],user_age,color='#052B6C',alpha=0.8,align='center',edgecolor='white')
plt.xlabel('年龄分组')
plt.ylabel('租赁次数')
plt.title('Citi Bike用户年龄分布')
plt.legend(['次数'],loc='upper right')
plt.grid(color='#95a5a6',linestyle='--',linewidth=1,axis='y',alpha=0.4)
plt.xticks(a,('少年','青年','中年','老年'))

([<matplotlib.axis.XTick at 0x281198827f0>,
 <a list of 4 Text xticklabel objects>)

# 用户会员类别饼图

In [307]:
user_type = cb.groupby('usertype')['bikeid'].agg(len)/cb['bikeid'].count()*100

In [308]:
plt.rc('font',family='STXihei',size=15)
colors = ['#EA1F29','#39A2E1']
name=['Customer','Subscriber']
plt.pie(user_type,labels=name,colors=colors,explode=(0,0),startangle=43,autopct='%1.1f%%')
plt.title('Citi Bike用户类别占比')
plt.legend(['Customer','Subscriber'],loc='upper left')

# 用户的骑行时间及速度

## 24小时中各时段骑行数

In [12]:
#对starttime字段进行分列,然后拼接到原数据表中
time_split = pd.DataFrame((x.split(' ') for x in cb5.starttime),index=cb5.index,columns=['start_date','start_time'])
cb5 = pd.merge(cb5,time_split,right_index=True,left_index=True)

In [13]:
cb5['start_time']=pd.to_datetime(cb5['start_time'])
cb5 = cb5.set_index('start_time')
star_hour = cb5.resample('H',how=len)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\__main__.py:3: FutureWarning: how in .resample() is deprecated
the new syntax is .resample(...)..apply(<func>)
  app.launch_new_instance()


In [16]:
ride_hour = star_hour['bikeid']

In [21]:
plt.rc('font',family='STXihei',size=15)

In [23]:
a= np.array(np.arange(24))

In [25]:
plt.plot(ride_hour,'8',ride_hour,'g-',color='#052B6C',linewidth=3,markeredgewidth=3,markeredgecolor='#052B6C',alpha=0.8)

## 骑行时间长度的分布

In [30]:
time_max = cb5['tripduration'].max()

In [34]:
bins = [0,300,600,1200,1800,2700,time_max]

In [35]:
tripduration_labels = ['5分钟','10分钟','20分钟','30分钟','45分钟','更长时间']

In [36]:
cb5['group_tripduration'] = pd.cut(cb5['tripduration'],bins,labels=tripduration_labels)

In [38]:
group_minute = cb5.groupby('group_tripduration')['group_tripduration'].agg(len)

In [40]:
plt.rc('font',family='STXihei',size=15)
a = np.array([1,2,3,4,5,6])
plt.bar([1,2,3,4,5,6],group_minute,color='#9F713F',alpha=0.8,align='center',edgecolor='white')
plt.xlabel('时间分组')
plt.ylabel('骑行次数')
plt.title('Citi Bike骑行时间分布')
plt.legend(['时间'],loc='upper right')
plt.grid(color='#95a5a6',linestyle='--',linewidth=1,axis='y',alpha = 0.4)
plt.xticks(a,('5分钟','10分钟','20分钟','30分钟','45分钟','更长时间'))
plt.show()

## 平均骑行速度

#### 根据 开始和结束站点的经纬度 求出路程长度，最后除以时间得出速度。（不准确没有考虑具体城市路线）

In [41]:
from math import radians,cos,sin,asin,sqrt

In [42]:
#通过经纬度计算距离的函数
def haversine(lon1,lat1,lon2,lat2): #经度1，纬度1，经度2，纬度2（十进制）
    '''
    Calculate the great circle distance between two points 
    on the earth(specified in decimal degrees)
    '''
    #将十进制转化为弧度
    lon1 = map(radians,np.array(lon1))
    lat1 = map(radians,np.array(lat1))
    lon2 = map(radians,np.array(lon2))
    lat2 = map(radians,np.array(lat2))
    lon1 = np.array(list(lon1)).reshape(-1,1)
    lon2 = np.array(list(lon2)).reshape(-1,1)
    lat1 = np.array(list(lat1)).reshape(-1,1)
    lat2 = np.array(list(lat2)).reshape(-1,1)
    #haversine公式
    dlon = lon2 - lon1
    dlat = lat2 - lat1
    a = np.sin(dlat/2)**2 + np.cos(lat1) * np.cos(lat2) *np.sin(dlon/2) **2
    c = 2 * np.arcsin(np.sqrt(a))
    r = 6371 #地球平均半径，单位为公里
    return c * r * 1000

In [46]:
#计算每次骑行的米数并增加骑行距离的字段
cb5['meter'] = haversine(cb5['start station longitude'],cb5['start station latitude'],cb5['end station longitude'],cb5['end station latitude'])


In [47]:
#将原数据表中的骑行时间由秒转化为小时
cb5['duration_hour'] = cb5['tripduration']/3600

In [48]:
#将米转化成公里，并计算出速度
cb5['speed'] = cb5['meter']/1000/cb5['duration_hour']

In [49]:
#现在我们有了每次骑行的速度，还要计算出用户平均的骑行速度。

In [51]:
#将每次骑行的米数求和并转化为公里
km = cb5['meter'].sum()/1000

In [53]:
#将每次骑行的秒数求和并转化成小时
hour = cb5['tripduration'].sum()/3600

In [54]:
speed = km/hour

In [56]:
#平均速度为6.31公里/时
speed

6.3101247093495

## 骑行速度与年龄的关联
#### 以2015年5月数据为例

In [58]:
#计算并增加年龄字段
cb5['age'] = 2015-cb5['birth year']

In [59]:
#提取年龄和骑行速度字段
age_speed = cb5[['speed','age']]

In [60]:
#去除骑行速度为0的数据
age_speed = age_speed.dropna()

In [61]:
#年龄设置为自变量X
X = np.array(age_speed[['age']])

In [62]:
#速度设置为因变量Y
Y = np.array(age_speed[['speed']])

In [64]:
#导入线性回归库
from sklearn import linear_model
#将数据导入模型
clf = linear_model.LinearRegression()
clf.fit(X,Y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [65]:
#斜率
clf.coef_

array([[-0.02899706]])

In [66]:
#截距
clf.intercept_

array([ 10.02613732])

In [67]:
#R方
clf.score(X,Y)

0.011272777068772388

In [68]:
#20岁的骑行速度预测为9.4公里/时
clf.predict(20)

array([[ 9.44619622]])

In [ ]:
#50岁的骑行速度预测为8.6公里/时
clf.predict(50)